### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by henkmollema** [jeremiedecock/pyax12#2]
Hi there,

I came across your library and I wondered if it supports controlling Dynamixel AX-12 actuators using a Raspberry Pi as well?

**Comment by jeremiedecock** [comment]
Hi,

if you use an USB2Dynamixel to operate AX-12 actuators, then it should work on any Gnu/Linux operating system, including the ones commonly used with Raspberry Pi (Raspbian, etc.). The only thing you might worry about is getting the right device path of your USB2Dynamixel ("/dev/ttyUSB0" for instance), getting the right baudrate of your actuators (if changed) and knowing how to supply power to actuators (I can give more details on this if needed).

Things become a bit more complicated if you don't want to use USB2Dynamixel but instead directly connect AX-12 actuators to Raspberry Pi GPIOs. This is feasible but you will need to make a small electronic circuit to convert Raspberry Pi UART signals (on RX and TX pins) to the half-duplex ones as explained here: http://support.robotis.com/en/product/dynamixel/dxl_ax_main.htm.

More information about USB2Dynamixel here: http://support.robotis.com/en/product/auxdevice/interface/usb2dxl_manual.htm.

I hope it answer your question.

**Comment by henkmollema** [comment]
I'm trying to control the servo's through GPIO. I'm having trouble setting changing the direction pin however, as your library does not support it, obviously. I'm not sure whether I'll use the source of your library and add GPIO support or use another library in stead.

**Comment by jeremiedecock** [comment]
Then I guess you already have a circuit that converts full-duplex into half-duplex (using 74HC126/74HC04 or 74LS241 chips).

For the 74LS241, it's well explained here: http://www.oppedijk.com/robotics/control-dynamixel-with-raspberrypi.

By the way, adding GPIO support in my library is planed and should be quite easy ; obviously you only need to add few lines in `pyax12.connection.Connection.__init__()` and `pyax12.connection.Connection.send()`. Feel free to add it. But anyway I may add this feature in the following days (I just need to buy the 74LS241 chip).

You may also consider the following library: https://github.com/thiagohersan/memememe/blob/master/Python/ax12/ax12.py.

Additional info for the 74LS241 here: http://www.memememememememe.me/the-dynamixel/.

**Comment by henkmollema** [comment]
Yes, we do have circuit providing the conversion. I tried implementing GPIO support. However, I can't get the timing between switching the direction pin and reading the bytes right. With the ax12 library from Thiago Hersan it does work, the delay is around 1ms then. The `send()` flow looks like this:

1. Switch the direction pin to high (TX)
1. Flush the port
1. Send the bytes using `write()`
1. Use a wait time of 400us (0.0004 sec) rather than the default wait time of pyAX12
1. Switch to direction pin back to low (RX)
1. Here should be the delay, however this is not the same as the ax12 library (1ms)
1. Start reading bytes

Perhaps you can find a way to create a reliable timing between the operations.

**Comment by jeremiedecock** [comment]
I will check that with an oscilloscope, when my conversion circuit will be ready.
Maybe in few weeks, I'm very busy these days.

**Comment by nickzano** [comment]
Was there ever any success using this library with a Raspberry Pi and a 74LS241?

**Comment by nickzano** [comment]
@jeremiedecock The problem with the https://github.com/thiagohersan/memememe/blob/master/Python/ax12/ax12.py library is it doesn't support Python 3.

**Comment by henkmollema** [comment]
@nickzano, we've ended up using https://github.com/thiagohersan/memememe/blob/master/Python/ax12/ax12.py.

**Comment by jeremiedecock** [comment]
@nickzano Yes, I added Raspberry Pi support through GPIO in v0.5

**Comment by jeremiedecock** [comment]
Check https://github.com/jeremiedecock/pyax12#hardware-setup and https://github.com/jeremiedecock/pyax12#example-usage for more information

**Comment by jeremiedecock** [comment]
@nickzano Yes, I added Raspberry Pi support through GPIO in v0.5

Check https://github.com/jeremiedecock/pyax12#hardware-setup and https://github.com/jeremiedecock/pyax12#example-usage for more information
